Quiz Screens Completed
sguevara11/TTPChallenge pull request #5
Opened 2017-02-17 00:40 UTC by mimicatcodes

2017-02-17 03:16 UTC, compilesandruns requested changes
Let me know if you have any additional questions!

2017-02-17 03:16 UTC, compilesandruns commented on TTPChallenge/CustomButton.swift
> +        }
Nice! 👍

2017-02-17 03:16 UTC, compilesandruns commented on TTPChallenge/Environment.swift
> +
ws

2017-02-17 03:16 UTC, compilesandruns commented on TTPChallenge/Environment.swift
> +}
Awesomeeee!

2017-02-17 03:16 UTC, compilesandruns commented on TTPChallenge/ITEngVC.swift
> +
ws

2017-02-17 03:16 UTC, compilesandruns commented on TTPChallenge/ITEngVC.swift
> +}
I just realized this code is the same as the other result VC's. Since each VC has the same buttons and same general layout, you can make a custom VC, say ResultVC and manipulate its attributes based on the result of the quiz. If you have any questions about this, please feel free to ask me. This abstraction would be a touch more complicated than the abstraction of the button but the idea is the same: to not repeat code.

2017-02-17 03:16 UTC, compilesandruns commented on TTPChallenge/MobileDevVC.swift
> +    var buttons = [UIButton]()
You can get rid of this guy. Doesn't look like you're using it anywhere else.

2017-02-17 03:16 UTC, compilesandruns commented on TTPChallenge/QuizMainVC.swift
> +
ws

2017-02-17 03:16 UTC, compilesandruns commented on TTPChallenge/QuizVC.swift
> +
you can throw the 3 lines above into the PersonalityTestCell class. And the first two, you can make IBInspectables

2017-02-17 03:16 UTC, compilesandruns commented on TTPChallenge/QuizVC.swift
> +
I think you can throw this onto the storyboard. I like to keep my VC's pretty bare, but it's a preference thing. I think if you use storyboard, use it to it's full advantage and de-clutter your code and if you use code for your UI, put ALL of it in code. But yeah, that all depends on your team and comfort and preferences.

2017-02-17 03:16 UTC, compilesandruns commented on TTPChallenge/QuizVC.swift
> +        }
Can you explain why you chose to add this method to the main dispatch queue? I don't know if it is necessary. You're not working on a background thread and it's not like you're calling a web service to update the UI. I'm not the most familiar with dispatch queues, but I would not use it unless the UI was getting updated because of the result of some API or web call. I'd like to hear your reasoning or what they taught you. I don't think this is "wrong," I just don't think you're benefiting from the thing that an async call should be doing.

2017-02-17 03:16 UTC, sguevara11 commented on TTPChallenge/QuizVC.swift
> +
Interesting and innovative solution to the quiz issue 👍

2017-02-17 03:16 UTC, sguevara11 commented on TTPChallenge/QuizVC.swift
> +            }
Same question about DispatchQueue method. Interested in hearing what role it plays in this situation

2017-02-17 03:31 UTC, mimicatcodes commented on TTPChallenge/MobileDevVC.swift
> +    var buttons = [UIButton]()
You're correct! Getting rid of them now :)

2017-02-17 03:32 UTC, mimicatcodes commented on TTPChallenge/QuizMainVC.swift
> +
Fixed

2017-02-17 03:32 UTC, mimicatcodes commented on TTPChallenge/MobileDevVC.swift
> +    var buttons = [UIButton]()
Fixed

2017-02-17 03:32 UTC, mimicatcodes commented on TTPChallenge/Environment.swift
> +}
Yay!

2017-02-17 03:32 UTC, mimicatcodes commented on TTPChallenge/ITEngVC.swift
> +
Fixed

2017-02-17 03:32 UTC, mimicatcodes commented on TTPChallenge/Environment.swift
> +
Fixed

2017-02-17 03:33 UTC, mimicatcodes commented on TTPChallenge/CustomButton.swift
> +        }
Thanks!

2017-02-17 03:37 UTC, mimicatcodes commented on TTPChallenge/QuizVC.swift
> +
Fixed

2017-02-17 03:38 UTC, mimicatcodes commented on TTPChallenge/QuizVC.swift
> +
:)

2017-02-17 04:18 UTC, mimicatcodes commented on TTPChallenge/ITEngVC.swift
> +}
Will ask you about this tmrw when we meet - I thought of the same and was actually doing it that way but also encountered some issues - Would like to talk about this in person!

2017-02-17 04:22 UTC, mimicatcodes commented on TTPChallenge/QuizVC.swift
> +            }
Hmmm this guy wasn't updating unless it was handled with DispatchQue. There was a concurrency issue that segue was done before passing data to the destination VC. So I put them in the main thread that the destination VC ( resultVC) could be updated properly on the UI. Any thoughts?

2017-02-17 04:24 UTC, mimicatcodes commented on TTPChallenge/QuizVC.swift
> +        }
You are correct. I had used this method to update a progress bar that previously attached to the view - which has been removed. This method is longer needed!

2017-02-17 04:37 UTC, mimicatcodes commented on TTPChallenge/QuizVC.swift
> +
Fixed!

2017-02-19 00:08 UTC, compilesandruns approved these changes

2017-02-20 20:52 UTC, closed without merging